


events {
        worker_connections 768;
        # multi_accept on;
}

stream {

    upstream cockroachdbnodes {
        server 127.0.0.1:26258;
        server 127.0.0.1:26259;
        server 127.0.0.1:26260;
    }

    upstream cockroachdbrack1 {
        server 127.0.0.1:28257;
        server 127.0.0.1:28260;
    }

    upstream cockroachdbrack2 {
        server 127.0.0.1:28258;
		server 127.0.0.1:28261;
    }

    upstream cockroachdbrack3 {
        server 127.0.0.1:28259;
		server 127.0.0.1:28262;
    }

   
server {
    listen 0.0.0.0:26258;
    proxy_pass cockroachdbrack1;
}
server {
    listen 0.0.0.0:26259;
    proxy_pass cockroachdbrack2;
}
server {
    listen 0.0.0.0:26260;
    proxy_pass cockroachdbrack3;
}

server {
    listen 0.0.0.0:26257;
    proxy_pass cockroachdbnodes;
}

}
http {
    upstream backend_group {
        server 127.0.0.1:18080;
        server 127.0.0.1:18081;
        server 127.0.0.1:18082;
        server 127.0.0.1:18083;
        server 127.0.0.1:18084;
        server 127.0.0.1:18085;
    }

    server {
        listen 8080;

        location / {
            proxy_pass https://backend_group;

            proxy_ssl_verify off;  # Disable SSL verification (use with caution)
            proxy_ssl_session_reuse on;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }


        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        types_hash_max_size 2048;
        # server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        default_type application/octet-stream;

        ##
        # SSL Settings
        ##

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        ##
        # Logging Settings
        ##

        access_log /opt/homebrew/var/log/nginx/access.log;

        ##
        # Gzip Settings
        ##

        gzip on;
     
}

