{
 "title": "Cockroach Replicas",
 "tags": [ "cockroachdb-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster name", "query": { "query": "sys_uptime{}" } },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{cluster=\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ranges: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(ranges{cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "ranges"
    },
    {
     "expr": "sum(sum(replicas_leaders{cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "raft leaders"
    },
    {
     "expr": "sum(sum(replicas_leaders_not_leaseholders{cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "raft leaders not lease holders"
    },
    {
     "expr": "sum(sum(ranges_unavailable{cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "unavailable"
    },
    {
     "expr": "sum(sum(ranges_underreplicated{cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "under-replicated"
    }
   ]
  },
  {
   "title": "Ranges: $node",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(ranges{cluster=\"$cluster\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}} - ranges"
    },
    {
     "expr": "sum(ranges_unavailable{cluster=\"$cluster\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}} - unavailable"
    }
   ]
  },
  {
   "title": "Raft Log: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(raftlog_behind{cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "raft log behind"
    },
    {
     "expr": "sum(sum(rate(raftlog_truncated{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance))",
     "legendFormat": "raft log truncated"
    },
    {
     "expr": "sum(sum(raftlog_selfbehind{cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "raft log self behind"
    }
   ]
  },
  {
   "title": "Raft Log Behind: $node",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sum(raftlog_behind{cluster=\"$cluster\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replicas: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(replicas{cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Replicas"
    },
    {
     "expr": "sum(sum(replicas_quiescent{cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Quiescent"
    },
    {
     "expr": "sum(sum(replicas{cluster=\"$cluster\",instance=~\"$node\"}) by (instance) - sum(replicas_quiescent{cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Quiescent Replicas: $node",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum(replicas_quiescent{cluster=\"$cluster\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replica leaseholders per node: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(replicas_leaseholders{cluster=\"$cluster\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replica leaseholders: $node",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "sum(replicas_leaseholders{cluster=\"$cluster\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replicas per node: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(replicas{cluster=\"$cluster\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replicas: $node",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "sum(replicas{cluster=\"$cluster\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Logical bytes per node: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(keybytes{cluster=\"$cluster\",instance=~\"$node\"}) by (instance) + sum(valbytes{cluster=\"$cluster\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Live bytes: $node",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "sum(livebytes{cluster=\"$cluster\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Keys written per second per node: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(rebalancing_writespersecond{cluster=\"$cluster\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Keys written per second: $node",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "sum(rebalancing_writespersecond{cluster=\"$cluster\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Range Ops: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(sum(rate(range_splits{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance))",
     "legendFormat": "splits"
    },
    {
     "expr": "sum(sum(rate(range_adds{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance))",
     "legendFormat": "adds"
    },
    {
     "expr": "sum(sum(rate(range_removes{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance))",
     "legendFormat": "removes"
    }
   ]
  },
  {
   "title": "Range Ops: $node",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "targets": [
    {
     "expr": "sum(rate(range_splits{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance) + sum(rate(range_adds{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance) + sum(rate(range_removes{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Snapshots: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ops", "label": "Snapshots" }
   ],
   "targets": [
    {
     "expr": "sum(sum(rate(range_snapshots_generated{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance))",
     "legendFormat": "Generated"
    },
    {
     "expr": "sum(sum(rate(range_snapshots_normal_applied{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance))",
     "legendFormat": "Normal-applied"
    },
    {
     "expr": "sum(sum(rate(range_snapshots_preemptive_applied{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance))",
     "legendFormat": "Preemptive-applied"
    },
    {
     "expr": "sum(replicas_reserved{cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "Reservations"
    }
   ]
  },
  {
   "title": "Snapshots: $node",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(range_snapshots_generated{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}} - generated"
    },
    {
     "expr": "sum(rate(range_snapshots_normal_applied{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance) + sum(rate(range_snapshots_preemptive_applied{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}} - applied"
    }
   ]
  }
 ]
}