{
 "title": "Cockroach SQL",
 "tags": [ "cockroachdb-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster name", "query": { "query": "sys_uptime{}" } },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SQL Connections: $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sql_conns{cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Connections: $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sql_conns{cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes: $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(sql_bytesin{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(sql_bytesout{ cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Bytes in/out: $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "rate(sql_bytesin{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - in"
    },
    {
     "expr": "rate(sql_bytesout{ cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - out"
    }
   ]
  },
  {
   "title": "Queries: $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sql_select_count{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "select"
    },
    {
     "expr": "sum(rate(sql_insert_count{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "insert"
    },
    {
     "expr": "sum(rate(sql_update_count{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "update"
    },
    {
     "expr": "sum(rate(sql_delete_count{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "Queries: $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "rate(sql_select_count{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]) + rate(sql_insert_count{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]) + rate(sql_update_count{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]) + rate(sql_delete_count{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SQL Exec Latency: 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sql_exec_latency:rate1m:quantile_99{cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transactions: $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "rate(sql_txn_begin_count{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]) + rate(sql_txn_commit_count{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]) + rate(sql_txn_abort_count{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]) + rate(sql_txn_rollback_count{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SQL Exec Latency: 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sql_exec_latency:rate1m:quantile_95{cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Schema Changes: $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "rate(sql_ddl_count{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transactions: $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sql_txn_begin_count{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "begin"
    },
    {
     "expr": "sum(rate(sql_txn_commit_count{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "commit"
    },
    {
     "expr": "sum(rate(sql_txn_abort_count{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "abort"
    },
    {
     "expr": "sum(rate(sql_txn_rollback_count{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "Schema changes: $node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sql_ddl_count{cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "DDL"
    }
   ]
  }
 ]
}