{
 "title": "Cockroach Storage",
 "tags": [ "cockroachdb-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster name", "query": { "query": "sys_uptime{}" } },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(sys_uptime{cluster=\"$cluster\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Capacity: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(sum(capacity{cluster=\"$cluster\",instance=~\"$node\"}) by (instance)) - sum(sum(capacity_available{cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(sum(capacity{cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "Capacity Used: $node",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "(sum(capacity{cluster=\"$cluster\",instance=~\"$node\"}) by (instance) - sum(capacity_available{cluster=\"$cluster\",instance=~\"$node\"}) by (instance)) / sum(capacity{cluster=\"$cluster\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Percentage of capacity used per node: All",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - sum(capacity_available{cluster=\"$cluster\",instance=~\"$node\"}) by (instance) / sum(capacity{cluster=\"$cluster\",instance=~\"$node\"}) by (instance) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Percentage of capacity used per node: All",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "1 - sum(capacity_available{cluster=\"$cluster\",instance=~\"$node\"}) by (instance) / sum(capacity{cluster=\"$cluster\",instance=~\"$node\"}) by (instance) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(sum(livebytes{cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Live"
    },
    {
     "expr": "sum(sum(sysbytes{cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Live Bytes: $node",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum(livebytes{cluster=\"$cluster\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Raft log commit latency: 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "raft_process_logcommit_latency:rate1m:quantile_99{cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read Amplification: $node",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "avg(rocksdb_read_amplification{cluster=\"$cluster\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Raft command commit latency: 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "raft_process_commandcommit_latency:rate1m:quantile_99{cluster=\"$cluster\",instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RocksDB SSTables: $node",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "sum(rocksdb_num_sstables{cluster=\"$cluster\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read Amplification: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(avg(rocksdb_read_amplification{cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Read Amplification"
    }
   ]
  },
  {
   "title": "File descriptor usage: $node",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "sum(sys_fd_open{cluster=\"$cluster\",instance=~\"$node\"}) by (instance) / sum(sys_fd_softlimit{cluster=\"$cluster\",instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Raft Engine Read Amplification: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(avg(raft_rocksdb_read_amplification{cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Raft Engine Read Amplification"
    }
   ]
  },
  {
   "title": "RocksDB SSTables: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(rocksdb_num_sstables{cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "SSTables"
    }
   ]
  },
  {
   "title": "Raft RocksDB SSTables: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(raft_rocksdb_num_sstables{cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "SSTables"
    }
   ]
  },
  {
   "title": "RocksDB cache hit rate: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rocksdb_block_cache_hits{cluster=\"$cluster\",instance=~\"$node\"} / (rocksdb_block_cache_hits{cluster=\"$cluster\",instance=~\"$node\"} + rocksdb_block_cache_misses{cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "{{instance}}:{{store}}"
    }
   ]
  },
  {
   "title": "Raft RocksDB cache hit rate: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "raft_rocksdb_block_cache_hits{cluster=\"$cluster\",instance=~\"$node\"} / (raft_rocksdb_block_cache_hits{cluster=\"$cluster\",instance=~\"$node\"} + raft_rocksdb_block_cache_misses{cluster=\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "{{instance}}:{{store}}"
    }
   ]
  },
  {
   "title": "File Descriptors: $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(sys_fd_open{cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Open FDs"
    },
    {
     "expr": "sum(sum(sys_fd_softlimit{cluster=\"$cluster\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "Limit"
    }
   ]
  }
 ]
}