{
 "title": "CRDB Console: Distributed",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "sys_uptime{}" } },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{},instance)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Batches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "batches" }
   ],
   "targets": [
    {
     "expr": "sum(rate(distsender_batches{}[$__rate_interval])) by (cluster)",
     "legendFormat": "Batch"
    },
    {
     "expr": "sum(rate(distsender_batches_partial{}[$__rate_interval])) by (cluster)",
     "legendFormat": "Partial Batches"
    }
   ]
  },
  {
   "title": "RPCs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "rpcs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(distsender_rpc_sent{}[$__rate_interval]))",
     "legendFormat": "RPCs Sent"
    },
    {
     "expr": "sum(rate(distsender_rpc_sent_local{}[$__rate_interval]))",
     "legendFormat": "Local Fast-path"
    }
   ]
  },
  {
   "title": "RPC Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "errors" }
   ],
   "targets": [
    {
     "expr": "sum(rate(distsender_rpc_sent_nextreplicaerror{}[$__rate_interval]))",
     "legendFormat": "Replica Errors"
    },
    {
     "expr": "sum(rate(distsender_errors_notleaseholder{}[$__rate_interval]))",
     "legendFormat": "Not Lease Holder Errors"
    }
   ]
  },
  {
   "title": "KV Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "transactions" }
   ],
   "targets": [
    {
     "expr": "sum(rate(txn_commits{}[$__rate_interval]))",
     "legendFormat": "Commited"
    },
    {
     "expr": "sum(rate(txn_commits1PC{}[$__rate_interval]))",
     "legendFormat": "Fast-path Commited"
    },
    {
     "expr": "sum(rate(txn_aborts{}[$__rate_interval]))",
     "legendFormat": "Aborted"
    }
   ]
  },
  {
   "title": "KV Transaction Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "restarts" }
   ],
   "targets": [
    {
     "expr": "sum(rate(txn_restarts_writetooold{}[$__rate_interval]))",
     "legendFormat": "Write Too Old"
    },
    {
     "expr": "sum(rate(txn_restarts_writetoooldmulti{}[$__rate_interval]))",
     "legendFormat": "Write Too Old (multiple)"
    },
    {
     "expr": "sum(rate(txn_restarts_serializable{}[$__rate_interval]))",
     "legendFormat": "Forwarded Timestamp (iso=serializable)"
    },
    {
     "expr": "sum(rate(txn_restarts_asyncwritefailure{}[$__rate_interval]))",
     "legendFormat": "Async Consensus Failure"
    },
    {
     "expr": "sum(rate(txn_restarts_readwithinuncertainty{}[$__rate_interval]))",
     "legendFormat": "Read Within Uncertainty Interval"
    },
    {
     "expr": "sum(rate(txn_restarts_txnaborted{}[$__rate_interval]))",
     "legendFormat": "Aborted"
    },
    {
     "expr": "sum(rate(txn_restarts_txnpush{}[$__rate_interval]))",
     "legendFormat": "Push Failure"
    },
    {
     "expr": "sum(rate(txn_restarts_unknown{}[$__rate_interval]))",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "KV Transactional Durations: 99th percentile",
   "type": "graph",
   "description": "The 99th percentile of transaction durations over a 1 minute period.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ns", "label": "transaction duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(txn_durations_bucket{}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "KV Transaction Durations: 90th percentile",
   "type": "graph",
   "description": "The 90th percentile of transaction durations over a 1 minute period.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "ns", "label": "transaction duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(txn_durations_bucket{}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Heartbeat Latency: 99th percentile ",
   "type": "graph",
   "description": "The 99th percentile of latency to heartbeat a node's internal liveness record over a 1 minute period.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "ns", "label": "heartbeat latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(liveness_heartbeatlatency_bucket{}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Heartbeat Latency: 90th percentile",
   "type": "graph",
   "description": "The 90th percentile of latency to heartbeat a node's internal liveness record over a 1 minute period.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "ns", "label": "heartbeat latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90,rate(liveness_heartbeatlatency_bucket{}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}