{
 "title": "LesFleurs",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Les Fleurs", "type": "canvas", "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 } },
  {
   "title": " AppServer & DB Availability",
   "type": "canvas",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "round(sum((sys_uptime{kubernetes_namespace=\"cockroachdb\"} or vector(0))) / sum((sys_uptime{ kubernetes_namespace=\"cockroachdb\"} or vector(1))))",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(sum(process_start_time_seconds{app=\"lesfleurs\", component=\"appserver\"} or vector(0))/  sum(process_start_time_seconds{app=\"lesfleurs\", component=\"appserver\"} or vector(1)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# of Flowers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "select count(*) from flowers" }
   ]
  },
  {
   "title": "# of Ratings",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "Select count(*) from Ratings" }
   ]
  },
  {
   "title": "Avg. Rating",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "Select AVG(stars) from Ratings" }
   ]
  },
  {
   "title": "Flowers in APAC",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select count(*) from flowers where origin='APAC'"
    }
   ]
  },
  {
   "title": "Flowers in AMERICAS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select count(*) from flowers where origin='AMERICAS'"
    }
   ]
  },
  {
   "title": "Flowers in EMEA",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select count(*) from flowers where origin='EMEA'"
    }
   ]
  },
  {
   "title": "SQL Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sql_select_count{kubernetes_namespace=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "select"
    },
    {
     "expr": "sum(rate(sql_insert_count{kubernetes_namespace=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "insert"
    },
    {
     "expr": "sum(rate(sql_update_count{kubernetes_namespace=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "update"
    },
    {
     "expr": "sum(rate(sql_delete_count{kubernetes_namespace=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sql_txn_begin_count{kubernetes_namespace=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "begin"
    },
    {
     "expr": "sum(rate(sql_txn_commit_count{kubernetes_namespace=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "commit"
    },
    {
     "expr": "sum(rate(sql_txn_abort_count{kubernetes_namespace=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "abort"
    },
    {
     "expr": "sum(rate(sql_txn_rollback_count{kubernetes_namespace=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "CockroachDB Nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(liveness_livenodes{kubernetes_namespace=\"cockroachdb\"})",
     "legendFormat": "Live nodes (node liveness heartbeats)"
    }
   ]
  },
  {
   "title": "Number of Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(route) (rate(http_request_duration_ms_count{app=\"lesfleurs\"} [1m])*60)",
     "legendFormat": "{{route}}, {{status}}"
    }
   ]
  },
  {
   "title": "Average Duration in ms per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "sum by(route) (irate(http_request_duration_ms_sum{app=\"lesfleurs\"}[1m]) / irate(http_request_duration_ms_count{app=\"lesfleurs\"} [1m]))",
     "legendFormat": "{{route}}, {{status}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 16, "w": 9, "x": 15, "y": 17 } },
  {
   "title": "HTTP Errors per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "(irate(http_request_duration_ms_count{app=\"lesfleurs\", status=~\"[45].*\"}[1m]) * 60) or vector(0)",
     "legendFormat": "{{route}}, {{status}}"
    }
   ]
  },
  {
   "title": "Total HTTP Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "http_request_duration_ms_count{app=\"lesfleurs\", status=~\"[45].*\"} or vector(0)",
     "legendFormat": "{{route}}, {{status}}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{app=\"lesfleurs\"}  |= `rror`"
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "{app=\"lesfleurs\"} |= ``"
    }
   ]
  }
 ]
}