{
 "title": "CRDB Console: Queues ",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "sys_uptime{}" } },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{},instance)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Queue Processing Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "failures" }
   ],
   "targets": [
    {
     "expr": "sum(rate(queue_gc_process_failure{}[$__rate_interval]))",
     "legendFormat": "GC"
    },
    {
     "expr": "sum(rate(queue_replicagc_process_failure{}[$__rate_interval]))",
     "legendFormat": "Replica GC"
    },
    {
     "expr": "sum(rate(queue_replicate_process_failure{}[$__rate_interval]))",
     "legendFormat": "Replication"
    },
    {
     "expr": "sum(rate(queue_split_process_failure{}[$__rate_interval]))",
     "legendFormat": "Split"
    },
    {
     "expr": "sum(rate(queue_consistency_process_failure{}[$__rate_interval]))",
     "legendFormat": "Consistency"
    },
    {
     "expr": "sum(rate(queue_raftlog_process_failure{}[$__rate_interval]))",
     "legendFormat": "Raft Log"
    },
    {
     "expr": "sum(rate(queue_raftsnapshot_process_failure{}[$__rate_interval]))",
     "legendFormat": "Raft Snapshot"
    },
    {
     "expr": "sum(rate(queue_tsmaintenance_process_failure{}[$__rate_interval]))",
     "legendFormat": "Time Series Maintenance"
    }
   ]
  },
  {
   "title": "Queue Processing Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ns", "label": "processing time" }
   ],
   "targets": [
    {
     "expr": "sum(rate(queue_gc_processingnanos{}[$__rate_interval]))",
     "legendFormat": "GC"
    },
    {
     "expr": "sum(rate(queue_replicagc_processingnanos{}[$__rate_interval]))",
     "legendFormat": "Replica GC"
    },
    {
     "expr": "sum(rate(queue_replicate_processingnanos{}[$__rate_interval]))",
     "legendFormat": "Replication"
    },
    {
     "expr": "sum(rate(queue_split_processingnanos{}[$__rate_interval]))",
     "legendFormat": "Split"
    },
    {
     "expr": "sum(rate(queue_consistency_processingnanos{}[$__rate_interval]))",
     "legendFormat": "Consistency"
    },
    {
     "expr": "sum(rate(queue_raftlog_processingnanos{}[$__rate_interval]))",
     "legendFormat": "Raft Log"
    },
    {
     "expr": "sum(rate(queue_raftsnapshot_processingnanos{}[$__rate_interval]))",
     "legendFormat": "Raft Snapshot"
    },
    {
     "expr": "sum(rate(queue_tsmaintenance_processingnanos{}[$__rate_interval]))",
     "legendFormat": "Time Series Maintenance"
    }
   ]
  },
  {
   "title": "Replica GC Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "actions" }
   ],
   "targets": [
    {
     "expr": "sum(rate(queue_gc_info_transactionspangccommitted{}[$__rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "sum(rate(queue_gc_info_transactionspangcpending{}[$__rate_interval]))",
     "legendFormat": "Pending Actions"
    },
    {
     "expr": "sum(rate(queue_replicate_removedeadreplica{}[$__rate_interval]))",
     "legendFormat": "Replicas Removed / sec"
    }
   ]
  },
  {
   "title": "Replication Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "actions" }
   ],
   "targets": [
    {
     "expr": "sum(rate(queue_replicate_process_success{}[$__rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "sum(rate(queue_replicate_pending{}[$__rate_interval]))",
     "legendFormat": "Pending Actions"
    },
    {
     "expr": "sum(rate(queue_replicate_addreplica{}[$__rate_interval]))",
     "legendFormat": "Replicas Added / sec"
    },
    {
     "expr": "sum(rate(queue_replicate_removereplica{}[$__rate_interval]))",
     "legendFormat": "Replicas Removed / sec"
    },
    {
     "expr": "sum(rate(queue_replicate_removedeadreplica{}[$__rate_interval]))",
     "legendFormat": "Dead Replicas Removed / sec"
    },
    {
     "expr": "sum(rate(queue_replicate_removelearnerreplica{}[$__rate_interval]))",
     "legendFormat": "Learner Replicas Removed / sec"
    },
    {
     "expr": "sum(rate(queue_replicate_rebalancereplica{}[$__rate_interval]))",
     "legendFormat": "Replicas Rebalanced / sec"
    },
    {
     "expr": "sum(rate(queue_replicate_transferlease{}[$__rate_interval]))",
     "legendFormat": "Leases Transferred / sec"
    },
    {
     "expr": "sum(rate(queue_replicate_purgatory{}[$__rate_interval]))",
     "legendFormat": "Replicas in Purgatory"
    }
   ]
  },
  {
   "title": "Split Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "actions" }
   ],
   "targets": [
    {
     "expr": "sum(rate(queue_split_process_success{}[$__rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "sum(rate(queue_split_pending{}[$__rate_interval]))",
     "legendFormat": "Pending Actions"
    }
   ]
  },
  {
   "title": "Merge Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "actions" }
   ],
   "targets": [
    {
     "expr": "sum(rate(queue_merge_process_success{}[$__rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "sum(rate(queue_merge_pending{}[$__rate_interval]))",
     "legendFormat": "Pending Actions"
    }
   ]
  },
  {
   "title": "GC Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "actions" }
   ],
   "targets": [
    {
     "expr": "sum(rate(queue_gc_process_success{}[$__rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "sum(rate(queue_gc_pending{}[$__rate_interval]))",
     "legendFormat": "Pending Actions"
    }
   ]
  },
  {
   "title": "Raft Log Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "actions" }
   ],
   "targets": [
    {
     "expr": "sum(rate(queue_raftlog_process_success{}[$__rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "sum(rate(queue_raftlog_pending{}[$__rate_interval]))",
     "legendFormat": "Pending Actions"
    }
   ]
  },
  {
   "title": "Raft Snapshot Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "actions" }
   ],
   "targets": [
    {
     "expr": "sum(rate(queue_raftsnapshot_process_success{}[$__rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "sum(rate(queue_raftsnapshot_pending{}[$__rate_interval]))",
     "legendFormat": "Pending Actions"
    }
   ]
  },
  {
   "title": "Consistency Checker Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short", "label": "actions" }
   ],
   "targets": [
    {
     "expr": "sum(rate(queue_consistency_process_success{}[$__rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "sum(queue_consistency_pending{})",
     "legendFormat": "Pending Actions"
    }
   ]
  },
  {
   "title": "Time Series Maintenance Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short", "label": "actions" }
   ],
   "targets": [
    {
     "expr": "sum(rate(queue_tsmaintenance_process_success{}[$__rate_interval]))",
     "legendFormat": "Successful Actions / sec"
    },
    {
     "expr": "sum(rate(queue_tsmaintenance_pending{}[$__rate_interval]))",
     "legendFormat": "Pending Actions"
    }
   ]
  }
 ]
}