{
 "title": "CRDB Console: Slow Requests ",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "sys_uptime{}" } },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{},instance)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Slow Raft Proposals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "proposals" }
   ],
   "targets": [
    { "expr": "sum(requests_slow_raft{})", "legendFormat": "Slow Raft Proposals" }
   ]
  },
  {
   "title": "Slow DistSender RPCs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "proposals" }
   ],
   "targets": [
    {
     "expr": "sum(requests_slow_distsender{})",
     "legendFormat": "Slow DistSender RPCs"
    }
   ]
  },
  {
   "title": "Slow Lease Acquisitions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "lease acquisitions" }
   ],
   "targets": [
    { "expr": "sum(requests_slow_lease{})", "legendFormat": "Slow Lease Acquisitions" }
   ]
  },
  {
   "title": "Slow Latch Acquisitions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "latch acquisitions" }
   ],
   "targets": [
    { "expr": "sum(requests_slow_latch{})", "legendFormat": "Slow Latch Acquisitions" }
   ]
  }
 ]
}