{
 "title": "CRDB Console: SQL ",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "sys_uptime{}" } },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{},instance)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Open SQL Sessions",
   "type": "graph",
   "description": "The total number of open SQL Sessions.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "connections" }
   ],
   "targets": [
    { "expr": "sql_conns{}", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Open SQL Transactions",
   "type": "graph",
   "description": "The total number of SQL transactions currently open.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "transactions" }
   ],
   "targets": [
    { "expr": "sql_txns_open{}", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Active SQL Statements",
   "type": "graph",
   "description": "The total number of SQL statements currently running.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "queries" }
   ],
   "targets": [
    {
     "expr": "sum(sql_distsql_queries_active{})",
     "legendFormat": "Active Statements"
    }
   ]
  },
  {
   "title": "SQL Byte Traffic",
   "type": "graph",
   "description": "The total amount of SQL client network traffic in bytes per second.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes", "label": "byte traffic" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_bytesin{}[$__rate_interval]))",
     "legendFormat": "Bytes In"
    },
    {
     "expr": "sum(rate(sql_bytesout{}[$__rate_interval]))",
     "legendFormat": "Bytes Out"
    }
   ]
  },
  {
   "title": "SQL Statements",
   "type": "graph",
   "description": "A moving average of the # of SELECT, INSERT, UPDATE, and DELETE statements successfully executed per second.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "queries" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_select_count{}[$rate_interval]))",
     "legendFormat": "Selects"
    },
    {
     "expr": "sum(rate(sql_update_count{}[$rate_interval]))",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(rate(sql_insert_count{}[$rate_interval]))",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum(rate(sql_delete_count{}[$rate_interval]))",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "SQL Statement Errors",
   "type": "graph",
   "description": "The number of statements which returned a planning or runtime error.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "errors" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_failure_count{}[$__rate_interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "SQL Statement Contention",
   "type": "graph",
   "description": "The total number of SQL statements that experienced contention.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "queries" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_distsql_contended_queries_count{}[$__rate_interval]))",
     "legendFormat": "Contention"
    }
   ]
  },
  {
   "title": "Active Flows for Distributed SQL Statements",
   "type": "graph",
   "description": "The number of flows on each node contributing to currently running distributed SQL statements.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "flows" }
   ],
   "targets": [
    {
     "expr": "rate(sql_distsql_flows_active{}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Service Latency: SQL, 99th percentile",
   "type": "graph",
   "description": "Over the last minute, this node executed 99% of queries within this time. This time does not include network latency between the node and client.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "ns", "label": "latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(sql_service_latency_bucket{}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Service Latency: SQL, 90th percentile",
   "type": "graph",
   "description": "Over the last minute, this node executed 90% of queries within this time. This time does not include network latency between the node and client.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "ns", "label": "latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(sql_service_latency_bucket{}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "KV Execution Latency: 99th percentile",
   "type": "graph",
   "description": "The 99th percentile of latency between query requests and responses over a 1 minute period. Values are displayed individually for each node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "µs", "label": "latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(exec_latency_bucket{}[$rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "KV Execution Latency: 90th percentile",
   "type": "graph",
   "description": "The 90th percentile of latency between query requests and responses over a 1 minute period. Values are displayed individually for each node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "ns", "label": "latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(exec_latency_bucket{}[$rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "description": "The total number of transactions initiated, committed, rolled back, or aborted per second.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short", "label": "latency" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_txn_begin_count{}[$rate_interval]))",
     "legendFormat": "Begin"
    },
    {
     "expr": "sum(rate(sql_txn_commit_count{}[$rate_interval]))",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(rate( sql_txn_rollback_count{}[$rate_interval]))",
     "legendFormat": "Rollbacks"
    },
    {
     "expr": "sum(rate(sql_txn_abort_count{}[$rate_interval]))",
     "legendFormat": "Aborts"
    }
   ]
  },
  {
   "title": "Transaction Latency: 99th percentile",
   "type": "graph",
   "description": "The 99th percentile of total transaction time over a 1 minute period. Values are displayed individually for each node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "µs", "label": "latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(sql_txn_latency_bucket{}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transaction Latency: 90th percentile",
   "type": "graph",
   "description": "The 90th percentile of total transaction time over a 1 minute period. Values are displayed individually for each node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "ns", "label": "latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90,rate(sql_txn_latency_bucket{}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SQL Memory",
   "type": "graph",
   "description": "The current amount of allocated SQL memory. This amount is what is compared against the node's --max-sql-memory flag.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "bytes", "label": "allocation bytes" }
   ],
   "targets": [
    { "expr": "sql_mem_root_current{}", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Schema Changes",
   "type": "graph",
   "description": "The total number of DDL statements per second",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "short", "label": "statements" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_ddl_count{}[$rate_interval]))  ",
     "legendFormat": "DDL Statements"
    }
   ]
  },
  {
   "title": "Statement Denials: Cluster Settings",
   "type": "graph",
   "description": "The total number of statements denied per second due to a [cluster setting](https://www.cockroachlabs.com/docs/v21.1/cluster-settings.html) in the format feature.statement_type.enabled = FALSE.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "short", "label": "statements" }
   ],
   "targets": [
    {
     "expr": "rate(sql_feature_flag_denial{}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}