{
 "title": "Heartrates",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "IoT with CockroachDB",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"http://www.cockroachlabs.com/img/iot-diagram.png\"/>"
   }
  },
  {
   "title": "Device Metadata",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT distinct manufacturer, devicetype, deviceid, username FROM hrg LIMIT 50 "
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "{app=~\".+\"} "
    }
   ]
  },
  {
   "title": "Heartrate over Time  (BPM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"id\",'2s'),\n  avg(\"hr\") AS \"HR\",\n  username\nFROM hrg\nWHERE $__timeFilter(\"id\")\nGROUP BY time, username\nORDER BY time"
    }
   ]
  },
  {
   "title": "Location",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT  $__timeGroupAlias(\"id\",'1s'), avg(\"hr\") AS \"heartrate\", (longitude) AS \"longitude\",  (latitude) AS \"latitude\" FROM hrg WHERE $__timeFilter(\"id\") GROUP BY time, longitude, latitude ORDER BY time\n"
    }
   ]
  },
  {
   "title": "Pace over Time  (min/km)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"id\",'2s'),\n  avg(\"speed\")*16.666667 AS \"Pace\",\n  username\nFROM hrg\nWHERE $__timeFilter(\"id\")\nGROUP BY time, username\nORDER BY time"
    }
   ]
  },
  {
   "title": "Speed over Time  (min/km)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"id\",'2s'),\n  avg(\"speed\") AS \"Speed\",\n  username\nFROM hrg\nWHERE $__timeFilter(\"id\")\nGROUP BY time, username\nORDER BY time"
    }
   ]
  },
  {
   "title": "Last Heartrate (bpm)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"id\",'1m'),\n  avg(\"hr\") AS \"HR\",\n  username\nFROM hrg\nWHERE $__timeFilter(\"id\")\nGROUP BY time, username\nORDER BY time"
    }
   ]
  }
 ]
}