{
 "title": "TheGym",
 "time": { "from": "now-1h", "to": "now+1h" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Loki Runs",
   "type": "text",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://storage.googleapis.com/thegym-public/thegym.jpg\"/>"
   }
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 } },
  {
   "title": "Location",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT  $__timeGroupAlias(\"id\",'1s'), avg(\"hr\") AS \"heartrate\", (longitude) AS \"longitude\",  (latitude) AS \"latitude\" FROM hrg WHERE $__timeFilter(\"id\") GROUP BY time, longitude, latitude ORDER BY time\n"
    }
   ]
  },
  {
   "title": "Heartrate over Time  (BPM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"id\",'2s'),\n  avg(\"hr\") AS \"HR\",\n  username\nFROM hrg\nWHERE $__timeFilter(\"id\")\nGROUP BY time, username\nORDER BY time"
    }
   ]
  },
  {
   "title": "Pace over Time  (min/km)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"id\",'2s'),\n  avg(\"speed\")*16.666667 AS \"Pace\",\n  username\nFROM hrg\nWHERE $__timeFilter(\"id\")\nGROUP BY time, username\nORDER BY time"
    }
   ]
  },
  {
   "title": "Speed over Time  (min/km)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"id\",'2s'),\n  avg(\"speed\") AS \"Speed\",\n  username\nFROM hrg\nWHERE $__timeFilter(\"id\")\nGROUP BY time, username\nORDER BY time"
    }
   ]
  },
  {
   "title": "Last Heartrate (bpm)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"id\",'1m'),\n  avg(\"hr\") AS \"HR\",\n  username\nFROM hrg\nWHERE $__timeFilter(\"id\")\nGROUP BY time, username\nORDER BY time"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{app=~\".+\"} "
    }
   ]
  }
 ]
}