{
 "title": "TheGym - Infra",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": " ",
   "type": "canvas",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "round(sum(DBAvailability{app=\"thegym\", service=\"heartrate-persister-kafka-consumer\"} or vector(0)))",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(sum(process_start_time_seconds{app=\"thegym\", service=\"lokiruns-local\"} or vector(0))/  sum(process_start_time_seconds{app=\"thegym\", service=\"lokiruns-local\"} or vector(1)))",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(sum(process_start_time_seconds{app=\"thegym\", service=\"heartrate-persister-kafka-producer\"} or vector(0))/  sum(process_start_time_seconds{app=\"thegym\", service=\"heartrate-persister-kafka-producer\"} or vector(1)))",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(sum(app_agent_receiver_logs_total{agent_hostname=\"localhost:12345\"}  or vector(0))/  sum(app_agent_receiver_logs_total{agent_hostname=\"localhost:12345\"}  or vector(1)))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum((kafka_server_replicamanager_leadercount{job=~\".+\",instance=~\".+\"} or vector(0))/ (kafka_server_replicamanager_leadercount{job=~\".+\",instance=~\".+\"} or vector(1)))",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(sum(process_start_time_seconds{app=\"thegym\", service=\"heartrate-persister-kafka-consumer\"} or vector(0))/  sum(process_start_time_seconds{app=\"thegym\", service=\"heartrate-persister-kafka-consumer\"} or vector(1)))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_messagesinpersec{topic=~\".*\"}[$__rate_interval]))*200",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Number of Heartrates",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SelecT count(id) from heartrates ;"
    }
   ]
  },
  {
   "title": "Max Heartrate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select Max(heartrate) from heartrates;"
    }
   ]
  },
  {
   "title": "Average Heartrate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select AVG(heartrate) from heartrates;"
    }
   ]
  },
  {
   "title": "CockroachDB Nodes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(up{app_kubernetes_io_name=\"cockroachdb\"})",
     "legendFormat": "All nodes"
    },
    {
     "expr": "count(up{app_kubernetes_io_name=\"cockroachdb\"} == 1)",
     "legendFormat": "Running nodes (prometheus)"
    },
    {
     "expr": "min(liveness_livenodes{app_kubernetes_io_name=\"cockroachdb\"})",
     "legendFormat": "Live nodes (node liveness heartbeats)"
    }
   ]
  },
  {
   "title": "CockroachDB SQL Queries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sql_select_count{}[$__rate_interval]))",
     "legendFormat": "select"
    },
    {
     "expr": "sum(rate(sql_insert_count{}[$__rate_interval]))",
     "legendFormat": "insert"
    },
    {
     "expr": "sum(rate(sql_update_count{}[$__rate_interval]))",
     "legendFormat": "update"
    },
    {
     "expr": "sum(rate(sql_delete_count{job=\"integrations/cockroachdb\",cluster=\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "Number of Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(route) (rate(http_request_duration_ms_count{app=\"thegym\"} [1m])*60)",
     "legendFormat": "{{route}}, {{status}}"
    }
   ]
  },
  {
   "title": "Kafka Messages In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesinpersec{topic=~\".*\"}[$__rate_interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Online Partitions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((kafka_server_replicamanager_partitioncount{job=~\".+\",instance=~\".+\"} or vector(0)) / (kafka_server_replicamanager_partitioncount{job=~\".+\",instance=~\".+\"} or vector(1)))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 } },
  {
   "title": "Average Duration in ms per Minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(route) (irate(http_request_duration_ms_sum{app=\"thegym\"}[1m]) / irate(http_request_duration_ms_count{app=\"thegym\"} [1m]))",
     "legendFormat": "{{route}}, {{status}}"
    }
   ]
  },
  {
   "title": "SQL Errors per Minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(SQLErrors{app=\"thegym\"}[1m])*60)",
     "legendFormat": "thegym"
    }
   ]
  },
  {
   "title": "HTTP Errors per Minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "irate(http_request_duration_ms_count{app=\"thegym\", status=~\"[45].*\"}[1m]) * 60",
     "legendFormat": "{{route}}, {{status}}"
    }
   ]
  },
  {
   "title": "Total HTTP Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "targets": [
    {
     "expr": "http_request_duration_ms_count{app=\"thegym\", status=~\"[45].*\"}",
     "legendFormat": "{{route}}, {{status}}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{app=\"thegym\"} |= `error` != `errorCode\":0`"
    }
   ]
  },
  {
   "title": "Traces ",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "limit": 20,
     "minDuration": "50ms",
     "query": "{.http.route!=\"/metrics\" && .http.target!=\"/metrics\"}"
    }
   ]
  },
  {
   "title": "Heartrates",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "{app=\"thegym\"} |= `info: {\"logs\":[{\"message\"` != `vitals`"
    }
   ]
  }
 ]
}